In [22]:
import cv2
import numpy as np

In [54]:
img = cv2.imread("/image1.png", cv2.IMREAD_UNCHANGED)
print(img[0][0])

[255 255 255 255]


In [84]:
thresh = 200

output = img.copy()
img_grey = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)


ret,thresh_img = cv2.threshold(img_grey, thresh, 255, cv2.THRESH_BINARY)

circles = cv2.HoughCircles(img_grey, cv2.HOUGH_GRADIENT, 1.3, 100)

if circles is not None:
   circles = np.round(circles[0, :]).astype("int")
   print(circles)
   for (x, y, r) in circles:
      cv2.circle(output, (x, y), r, (0, 255, 0, 255), -1)

cv2.imwrite("/circle.png", output)

[[460 255  68]
 [289 426  51]
 [632  86  71]]


True

In [93]:
all_horisontal_lines = list()
white = [255, 255, 255, 255]
transpar = [0,0,0,0]

def is_not_bg(coord):
  return (coord != white).any() and (coord != transpar).any()

max_len = 0;

for i in range(img.shape[0]):
  for j in range(img.shape[1]):
    if is_not_bg(img[i][j]):
      if j == 0 or (not is_not_bg(img[i][j - 1])):
        k = j
        cnt = 0
        while is_not_bg(img[i][k]):
          cnt += 1
          k += 1
        max_len = max(cnt, max_len)
        all_horisontal_lines.append((i, j, cnt))

horisontal_lines = list()
for elem in all_horisontal_lines:
  if elem[2] == max_len:
     horisontal_lines.append(elem)

[(162, 204, 512),
 (163, 204, 512),
 (164, 204, 512),
 (165, 204, 512),
 (166, 204, 512),
 (167, 204, 512),
 (168, 204, 512),
 (169, 204, 512),
 (170, 204, 512),
 (171, 204, 512),
 (172, 204, 512),
 (173, 204, 512),
 (174, 204, 512),
 (175, 204, 512),
 (176, 204, 512),
 (177, 204, 512),
 (178, 204, 512),
 (333, 204, 512),
 (334, 204, 512),
 (335, 204, 512),
 (336, 204, 512),
 (337, 204, 512),
 (338, 204, 512),
 (339, 204, 512),
 (340, 204, 512),
 (341, 204, 512),
 (342, 204, 512),
 (343, 204, 512),
 (344, 204, 512),
 (345, 204, 512),
 (346, 204, 512),
 (347, 204, 512),
 (348, 204, 512),
 (349, 204, 512)]

In [97]:
all_vertical_lines = list()
white = [255, 255, 255, 255]
transpar = [0,0,0,0]

def is_not_bg(coord):
  return (coord != white).any() and (coord != transpar).any()

max_len = 0;

for i in range(img.shape[0]):
  for j in range(img.shape[1]):
    if is_not_bg(img[i][j]):
      if i == 0 or (not is_not_bg(img[i - 1][j])):
        k = i
        cnt = 0
        while k != img.shape[0] and is_not_bg(img[k][j]):
          cnt += 1
          k += 1
        max_len = max(cnt, max_len)
        all_vertical_lines.append((i, j, cnt))

vertical_lines = list()
for elem in all_vertical_lines:
  if elem[2] == max_len:
     vertical_lines.append(elem)

In [98]:
vertical_lines

[(0, 366, 512),
 (0, 367, 512),
 (0, 368, 512),
 (0, 369, 512),
 (0, 370, 512),
 (0, 371, 512),
 (0, 372, 512),
 (0, 373, 512),
 (0, 374, 512),
 (0, 375, 512),
 (0, 376, 512),
 (0, 377, 512),
 (0, 378, 512),
 (0, 379, 512),
 (0, 380, 512),
 (0, 381, 512),
 (0, 382, 512),
 (0, 537, 512),
 (0, 538, 512),
 (0, 539, 512),
 (0, 540, 512),
 (0, 541, 512),
 (0, 542, 512),
 (0, 543, 512),
 (0, 544, 512),
 (0, 545, 512),
 (0, 546, 512),
 (0, 547, 512),
 (0, 548, 512),
 (0, 549, 512),
 (0, 550, 512),
 (0, 551, 512),
 (0, 552, 512),
 (0, 553, 512)]

In [115]:
#Make cells
border_cells = []

main_vert_lines = [(vertical_lines[0][0], horisontal_lines[0][1])]

for i in range(len(vertical_lines)):
  if i == 0 or i == len(vertical_lines) - 1:
    main_vert_lines.append(vertical_lines[i])
    continue
  if vertical_lines[i][1] - vertical_lines[i - 1][1] != 1 or vertical_lines[i + 1][1] - vertical_lines[i][1] != 1:
    main_vert_lines.append(vertical_lines[i])

main_vert_lines.append((vertical_lines[0][0], horisontal_lines[0][1] + horisontal_lines[0][2]))

main_horiz_lines = [(vertical_lines[0][0], horisontal_lines[0][1])]

for i in range(len(horisontal_lines)):
  if i == 0 or i == len(horisontal_lines) - 1:
    main_horiz_lines.append(horisontal_lines[i])
    continue
  if horisontal_lines[i][0] - horisontal_lines[i - 1][0] != 1 or horisontal_lines[i + 1][0] - horisontal_lines[i][0] != 1:
    main_horiz_lines.append(horisontal_lines[i])

main_horiz_lines.append((vertical_lines[0][0] + vertical_lines[0][2], horisontal_lines[0][1]))

for idx_h in range(len(main_horiz_lines)):
  for idx_v in range(len(main_vert_lines)):
    if idx_h % 2 == 0:
      if idx_v % 2 == 0:
        border_cells.append((main_horiz_lines[idx_h][0], main_vert_lines[idx_v][1]))
      else:
        border_cells.append((main_horiz_lines[idx_h + 1][0], main_vert_lines[idx_v][1]))

border_cells

[(0, 204),
 (162, 366),
 (0, 382),
 (162, 537),
 (0, 553),
 (162, 716),
 (178, 204),
 (333, 366),
 (178, 382),
 (333, 537),
 (178, 553),
 (333, 716),
 (349, 204),
 (512, 366),
 (349, 382),
 (512, 537),
 (349, 553),
 (512, 716)]

In [ ]:
what_in_cell = list() # 0 - nothing, 1 - cross, 2 -circle

for i in range(9):
  left_up = border_cells[i]
  right_down = border_cells[i + 1]

  mistake = 6

  c_x = right_up[1] - left_up[1]
  c_y = right_up[0] - left_up[0]

  cnt = 0
  for i in range(-mistake, mistake):
    for j in range(-mistake, mistake):
      if is_not_bg(img[c_y + i][c_x + j]):
        cnt += 1

  #did not make empty cells((((
  if cnt >= 2 * mistake:
    what_in_cell.append(1)
  else:
    what_in_cell.append(2)

  